/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VsIaGenerativaRouteImport } from './routes/vs-ia-generativa'
import { Route as VipPassRouteImport } from './routes/vip-pass'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as UneteAlEquipoRouteImport } from './routes/unete-al-equipo'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as SobreGuillermoRouteImport } from './routes/sobre-guillermo'
import { Route as Reestructura11RouteImport } from './routes/reestructura-1-1'
import { Route as PreciosRouteImport } from './routes/precios'
import { Route as PoliticasLegalesRouteImport } from './routes/politicas-legales'
import { Route as NewsletterRouteImport } from './routes/newsletter'
import { Route as MetodoIroRouteImport } from './routes/metodo-iro'
import { Route as LoginRouteImport } from './routes/login'
import { Route as KaironRouteImport } from './routes/kairon'
import { Route as InversoresRouteImport } from './routes/inversores'
import { Route as IndiceFriccionRouteImport } from './routes/indice-friccion'
import { Route as GStructRouteImport } from './routes/g-struct'
import { Route as GFrameRouteImport } from './routes/g-frame'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as DiagnosticoFriccionEjecutivaRouteImport } from './routes/diagnostico-friccion-ejecutiva'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as BloqueosRouteImport } from './routes/bloqueos'
import { Route as ArticulosRouteImport } from './routes/articulos'
import { Route as ApoyaElLanzamientoRouteImport } from './routes/apoya-el-lanzamiento'
import { Route as AliadosEtw2026RouteImport } from './routes/aliados-etw-2026'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as ArticulosIndexRouteImport } from './routes/articulos.index'
import { Route as MockupKaironHeroRouteImport } from './routes/mockup.kairon-hero'
import { Route as MockupCorporateHomeRouteImport } from './routes/mockup.corporate-home'
import { Route as LegalTerminosYCondicionesRouteImport } from './routes/legal.terminos-y-condiciones'
import { Route as LegalPoliticaDeReembolsosRouteImport } from './routes/legal.politica-de-reembolsos'
import { Route as LegalPoliticaDePrivacidadRouteImport } from './routes/legal.politica-de-privacidad'
import { Route as EnVsGenerativeAiRouteImport } from './routes/en.vs-generative-ai'
import { Route as EnVipPassRouteImport } from './routes/en.vip-pass'
import { Route as EnSupportTheLaunchRouteImport } from './routes/en.support-the-launch'
import { Route as EnRestructure11RouteImport } from './routes/en.restructure-1-1'
import { Route as EnPricingRouteImport } from './routes/en.pricing'
import { Route as EnNewsletterRouteImport } from './routes/en.newsletter'
import { Route as EnKaironRouteImport } from './routes/en.kairon'
import { Route as EnJoinTheTeamRouteImport } from './routes/en.join-the-team'
import { Route as EnIroMethodRouteImport } from './routes/en.iro-method'
import { Route as EnInvestorsRouteImport } from './routes/en.investors'
import { Route as EnGStructRouteImport } from './routes/en.g-struct'
import { Route as EnGFrameRouteImport } from './routes/en.g-frame'
import { Route as EnFrictionIndexRouteImport } from './routes/en.friction-index'
import { Route as EnExecutionBlocksRouteImport } from './routes/en.execution-blocks'
import { Route as EnEtw2026PartnersRouteImport } from './routes/en.etw-2026-partners'
import { Route as EnEnterpriseRouteImport } from './routes/en.enterprise'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnArticlesRouteImport } from './routes/en.articles'
import { Route as EnAboutGuillermoRouteImport } from './routes/en.about-guillermo'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ArticulosSlugRouteImport } from './routes/articulos.$slug'
import { Route as EnArticlesIndexRouteImport } from './routes/en.articles.index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as KaironVsNotionRouteImport } from './routes/kairon_.vs.notion'
import { Route as EnLegalTermsAndConditionsRouteImport } from './routes/en.legal.terms-and-conditions'
import { Route as EnLegalRefundPolicyRouteImport } from './routes/en.legal.refund-policy'
import { Route as EnLegalPrivacyPolicyRouteImport } from './routes/en.legal.privacy-policy'
import { Route as EnArticlesSlugRouteImport } from './routes/en.articles.$slug'
import { Route as ApiPublicPaypalSupportCreateOrderRouteImport } from './routes/api/public/paypal-support-create-order'
import { Route as ApiPublicPaypalSupportConfigRouteImport } from './routes/api/public/paypal-support-config'
import { Route as ApiPublicPaypalSupportCaptureOrderRouteImport } from './routes/api/public/paypal-support-capture-order'
import { Route as ApiPublicNewsletterSubscribeRouteImport } from './routes/api/public/newsletter-subscribe'
import { Route as ApiPublicGstructWaitlistCountRouteImport } from './routes/api/public/gstruct-waitlist-count'
import { Route as ApiPublicGstructWaitlistRouteImport } from './routes/api/public/gstruct-waitlist'
import { Route as ApiPublicDiagnosticoSubmitRouteImport } from './routes/api/public/diagnostico-submit'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicArticleCommentsRouteImport } from './routes/api/public/article-comments'
import { Route as AdminAdminWaitlistRouteImport } from './routes/_admin/admin.waitlist'
import { Route as AdminAdminSupportersRouteImport } from './routes/_admin/admin.supporters'
import { Route as AdminAdminReservasRouteImport } from './routes/_admin/admin.reservas'
import { Route as AdminAdminDiagnosticosRouteImport } from './routes/_admin/admin.diagnosticos'
import { Route as AdminAdminComentariosRouteImport } from './routes/_admin/admin.comentarios'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as EnKaironVsNotionRouteImport } from './routes/en.kairon_.vs.notion'

const VsIaGenerativaRoute = VsIaGenerativaRouteImport.update({
  id: '/vs-ia-generativa',
  path: '/vs-ia-generativa',
  getParentRoute: () => rootRouteImport,
} as any)
const VipPassRoute = VipPassRouteImport.update({
  id: '/vip-pass',
  path: '/vip-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const UneteAlEquipoRoute = UneteAlEquipoRouteImport.update({
  id: '/unete-al-equipo',
  path: '/unete-al-equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreGuillermoRoute = SobreGuillermoRouteImport.update({
  id: '/sobre-guillermo',
  path: '/sobre-guillermo',
  getParentRoute: () => rootRouteImport,
} as any)
const Reestructura11Route = Reestructura11RouteImport.update({
  id: '/reestructura-1-1',
  path: '/reestructura-1-1',
  getParentRoute: () => rootRouteImport,
} as any)
const PreciosRoute = PreciosRouteImport.update({
  id: '/precios',
  path: '/precios',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasLegalesRoute = PoliticasLegalesRouteImport.update({
  id: '/politicas-legales',
  path: '/politicas-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const NewsletterRoute = NewsletterRouteImport.update({
  id: '/newsletter',
  path: '/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodoIroRoute = MetodoIroRouteImport.update({
  id: '/metodo-iro',
  path: '/metodo-iro',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const KaironRoute = KaironRouteImport.update({
  id: '/kairon',
  path: '/kairon',
  getParentRoute: () => rootRouteImport,
} as any)
const InversoresRoute = InversoresRouteImport.update({
  id: '/inversores',
  path: '/inversores',
  getParentRoute: () => rootRouteImport,
} as any)
const IndiceFriccionRoute = IndiceFriccionRouteImport.update({
  id: '/indice-friccion',
  path: '/indice-friccion',
  getParentRoute: () => rootRouteImport,
} as any)
const GStructRoute = GStructRouteImport.update({
  id: '/g-struct',
  path: '/g-struct',
  getParentRoute: () => rootRouteImport,
} as any)
const GFrameRoute = GFrameRouteImport.update({
  id: '/g-frame',
  path: '/g-frame',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoFriccionEjecutivaRoute =
  DiagnosticoFriccionEjecutivaRouteImport.update({
    id: '/diagnostico-friccion-ejecutiva',
    path: '/diagnostico-friccion-ejecutiva',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const BloqueosRoute = BloqueosRouteImport.update({
  id: '/bloqueos',
  path: '/bloqueos',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosRoute = ArticulosRouteImport.update({
  id: '/articulos',
  path: '/articulos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApoyaElLanzamientoRoute = ApoyaElLanzamientoRouteImport.update({
  id: '/apoya-el-lanzamiento',
  path: '/apoya-el-lanzamiento',
  getParentRoute: () => rootRouteImport,
} as any)
const AliadosEtw2026Route = AliadosEtw2026RouteImport.update({
  id: '/aliados-etw-2026',
  path: '/aliados-etw-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosIndexRoute = ArticulosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticulosRoute,
} as any)
const MockupKaironHeroRoute = MockupKaironHeroRouteImport.update({
  id: '/mockup/kairon-hero',
  path: '/mockup/kairon-hero',
  getParentRoute: () => rootRouteImport,
} as any)
const MockupCorporateHomeRoute = MockupCorporateHomeRouteImport.update({
  id: '/mockup/corporate-home',
  path: '/mockup/corporate-home',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTerminosYCondicionesRoute =
  LegalTerminosYCondicionesRouteImport.update({
    id: '/legal/terminos-y-condiciones',
    path: '/legal/terminos-y-condiciones',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalPoliticaDeReembolsosRoute =
  LegalPoliticaDeReembolsosRouteImport.update({
    id: '/legal/politica-de-reembolsos',
    path: '/legal/politica-de-reembolsos',
    getParentRoute: () => rootRouteImport,
  } as any)
const LegalPoliticaDePrivacidadRoute =
  LegalPoliticaDePrivacidadRouteImport.update({
    id: '/legal/politica-de-privacidad',
    path: '/legal/politica-de-privacidad',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnVsGenerativeAiRoute = EnVsGenerativeAiRouteImport.update({
  id: '/en/vs-generative-ai',
  path: '/en/vs-generative-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const EnVipPassRoute = EnVipPassRouteImport.update({
  id: '/en/vip-pass',
  path: '/en/vip-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const EnSupportTheLaunchRoute = EnSupportTheLaunchRouteImport.update({
  id: '/en/support-the-launch',
  path: '/en/support-the-launch',
  getParentRoute: () => rootRouteImport,
} as any)
const EnRestructure11Route = EnRestructure11RouteImport.update({
  id: '/en/restructure-1-1',
  path: '/en/restructure-1-1',
  getParentRoute: () => rootRouteImport,
} as any)
const EnPricingRoute = EnPricingRouteImport.update({
  id: '/en/pricing',
  path: '/en/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const EnNewsletterRoute = EnNewsletterRouteImport.update({
  id: '/en/newsletter',
  path: '/en/newsletter',
  getParentRoute: () => rootRouteImport,
} as any)
const EnKaironRoute = EnKaironRouteImport.update({
  id: '/en/kairon',
  path: '/en/kairon',
  getParentRoute: () => rootRouteImport,
} as any)
const EnJoinTheTeamRoute = EnJoinTheTeamRouteImport.update({
  id: '/en/join-the-team',
  path: '/en/join-the-team',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIroMethodRoute = EnIroMethodRouteImport.update({
  id: '/en/iro-method',
  path: '/en/iro-method',
  getParentRoute: () => rootRouteImport,
} as any)
const EnInvestorsRoute = EnInvestorsRouteImport.update({
  id: '/en/investors',
  path: '/en/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGStructRoute = EnGStructRouteImport.update({
  id: '/en/g-struct',
  path: '/en/g-struct',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGFrameRoute = EnGFrameRouteImport.update({
  id: '/en/g-frame',
  path: '/en/g-frame',
  getParentRoute: () => rootRouteImport,
} as any)
const EnFrictionIndexRoute = EnFrictionIndexRouteImport.update({
  id: '/en/friction-index',
  path: '/en/friction-index',
  getParentRoute: () => rootRouteImport,
} as any)
const EnExecutionBlocksRoute = EnExecutionBlocksRouteImport.update({
  id: '/en/execution-blocks',
  path: '/en/execution-blocks',
  getParentRoute: () => rootRouteImport,
} as any)
const EnEtw2026PartnersRoute = EnEtw2026PartnersRouteImport.update({
  id: '/en/etw-2026-partners',
  path: '/en/etw-2026-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const EnEnterpriseRoute = EnEnterpriseRouteImport.update({
  id: '/en/enterprise',
  path: '/en/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnArticlesRoute = EnArticlesRouteImport.update({
  id: '/en/articles',
  path: '/en/articles',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutGuillermoRoute = EnAboutGuillermoRouteImport.update({
  id: '/en/about-guillermo',
  path: '/en/about-guillermo',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosSlugRoute = ArticulosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticulosRoute,
} as any)
const EnArticlesIndexRoute = EnArticlesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EnArticlesRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const KaironVsNotionRoute = KaironVsNotionRouteImport.update({
  id: '/kairon_/vs/notion',
  path: '/kairon/vs/notion',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLegalTermsAndConditionsRoute =
  EnLegalTermsAndConditionsRouteImport.update({
    id: '/en/legal/terms-and-conditions',
    path: '/en/legal/terms-and-conditions',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnLegalRefundPolicyRoute = EnLegalRefundPolicyRouteImport.update({
  id: '/en/legal/refund-policy',
  path: '/en/legal/refund-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnLegalPrivacyPolicyRoute = EnLegalPrivacyPolicyRouteImport.update({
  id: '/en/legal/privacy-policy',
  path: '/en/legal/privacy-policy',
  getParentRoute: () => rootRouteImport,
} as any)
const EnArticlesSlugRoute = EnArticlesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => EnArticlesRoute,
} as any)
const ApiPublicPaypalSupportCreateOrderRoute =
  ApiPublicPaypalSupportCreateOrderRouteImport.update({
    id: '/api/public/paypal-support-create-order',
    path: '/api/public/paypal-support-create-order',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaypalSupportConfigRoute =
  ApiPublicPaypalSupportConfigRouteImport.update({
    id: '/api/public/paypal-support-config',
    path: '/api/public/paypal-support-config',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaypalSupportCaptureOrderRoute =
  ApiPublicPaypalSupportCaptureOrderRouteImport.update({
    id: '/api/public/paypal-support-capture-order',
    path: '/api/public/paypal-support-capture-order',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicNewsletterSubscribeRoute =
  ApiPublicNewsletterSubscribeRouteImport.update({
    id: '/api/public/newsletter-subscribe',
    path: '/api/public/newsletter-subscribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGstructWaitlistCountRoute =
  ApiPublicGstructWaitlistCountRouteImport.update({
    id: '/api/public/gstruct-waitlist-count',
    path: '/api/public/gstruct-waitlist-count',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGstructWaitlistRoute =
  ApiPublicGstructWaitlistRouteImport.update({
    id: '/api/public/gstruct-waitlist',
    path: '/api/public/gstruct-waitlist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiagnosticoSubmitRoute =
  ApiPublicDiagnosticoSubmitRouteImport.update({
    id: '/api/public/diagnostico-submit',
    path: '/api/public/diagnostico-submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArticleCommentsRoute =
  ApiPublicArticleCommentsRouteImport.update({
    id: '/api/public/article-comments',
    path: '/api/public/article-comments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdminWaitlistRoute = AdminAdminWaitlistRouteImport.update({
  id: '/admin/waitlist',
  path: '/admin/waitlist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSupportersRoute = AdminAdminSupportersRouteImport.update({
  id: '/admin/supporters',
  path: '/admin/supporters',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReservasRoute = AdminAdminReservasRouteImport.update({
  id: '/admin/reservas',
  path: '/admin/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDiagnosticosRoute = AdminAdminDiagnosticosRouteImport.update({
  id: '/admin/diagnosticos',
  path: '/admin/diagnosticos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminComentariosRoute = AdminAdminComentariosRouteImport.update({
  id: '/admin/comentarios',
  path: '/admin/comentarios',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const EnKaironVsNotionRoute = EnKaironVsNotionRouteImport.update({
  id: '/en/kairon_/vs/notion',
  path: '/en/kairon/vs/notion',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aliados-etw-2026': typeof AliadosEtw2026Route
  '/apoya-el-lanzamiento': typeof ApoyaElLanzamientoRoute
  '/articulos': typeof ArticulosRouteWithChildren
  '/bloqueos': typeof BloqueosRoute
  '/contacto': typeof ContactoRoute
  '/diagnostico-friccion-ejecutiva': typeof DiagnosticoFriccionEjecutivaRoute
  '/enterprise': typeof EnterpriseRoute
  '/g-frame': typeof GFrameRoute
  '/g-struct': typeof GStructRoute
  '/indice-friccion': typeof IndiceFriccionRoute
  '/inversores': typeof InversoresRoute
  '/kairon': typeof KaironRoute
  '/login': typeof LoginRoute
  '/metodo-iro': typeof MetodoIroRoute
  '/newsletter': typeof NewsletterRoute
  '/politicas-legales': typeof PoliticasLegalesRoute
  '/precios': typeof PreciosRoute
  '/reestructura-1-1': typeof Reestructura11Route
  '/sobre-guillermo': typeof SobreGuillermoRoute
  '/teams': typeof TeamsRoute
  '/unete-al-equipo': typeof UneteAlEquipoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vip-pass': typeof VipPassRoute
  '/vs-ia-generativa': typeof VsIaGenerativaRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/en/about-guillermo': typeof EnAboutGuillermoRoute
  '/en/articles': typeof EnArticlesRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/enterprise': typeof EnEnterpriseRoute
  '/en/etw-2026-partners': typeof EnEtw2026PartnersRoute
  '/en/execution-blocks': typeof EnExecutionBlocksRoute
  '/en/friction-index': typeof EnFrictionIndexRoute
  '/en/g-frame': typeof EnGFrameRoute
  '/en/g-struct': typeof EnGStructRoute
  '/en/investors': typeof EnInvestorsRoute
  '/en/iro-method': typeof EnIroMethodRoute
  '/en/join-the-team': typeof EnJoinTheTeamRoute
  '/en/kairon': typeof EnKaironRoute
  '/en/newsletter': typeof EnNewsletterRoute
  '/en/pricing': typeof EnPricingRoute
  '/en/restructure-1-1': typeof EnRestructure11Route
  '/en/support-the-launch': typeof EnSupportTheLaunchRoute
  '/en/vip-pass': typeof EnVipPassRoute
  '/en/vs-generative-ai': typeof EnVsGenerativeAiRoute
  '/legal/politica-de-privacidad': typeof LegalPoliticaDePrivacidadRoute
  '/legal/politica-de-reembolsos': typeof LegalPoliticaDeReembolsosRoute
  '/legal/terminos-y-condiciones': typeof LegalTerminosYCondicionesRoute
  '/mockup/corporate-home': typeof MockupCorporateHomeRoute
  '/mockup/kairon-hero': typeof MockupKaironHeroRoute
  '/articulos/': typeof ArticulosIndexRoute
  '/en/': typeof EnIndexRoute
  '/admin/comentarios': typeof AdminAdminComentariosRoute
  '/admin/diagnosticos': typeof AdminAdminDiagnosticosRoute
  '/admin/reservas': typeof AdminAdminReservasRoute
  '/admin/supporters': typeof AdminAdminSupportersRoute
  '/admin/waitlist': typeof AdminAdminWaitlistRoute
  '/api/public/article-comments': typeof ApiPublicArticleCommentsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/diagnostico-submit': typeof ApiPublicDiagnosticoSubmitRoute
  '/api/public/gstruct-waitlist': typeof ApiPublicGstructWaitlistRoute
  '/api/public/gstruct-waitlist-count': typeof ApiPublicGstructWaitlistCountRoute
  '/api/public/newsletter-subscribe': typeof ApiPublicNewsletterSubscribeRoute
  '/api/public/paypal-support-capture-order': typeof ApiPublicPaypalSupportCaptureOrderRoute
  '/api/public/paypal-support-config': typeof ApiPublicPaypalSupportConfigRoute
  '/api/public/paypal-support-create-order': typeof ApiPublicPaypalSupportCreateOrderRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/en/legal/privacy-policy': typeof EnLegalPrivacyPolicyRoute
  '/en/legal/refund-policy': typeof EnLegalRefundPolicyRoute
  '/en/legal/terms-and-conditions': typeof EnLegalTermsAndConditionsRoute
  '/kairon/vs/notion': typeof KaironVsNotionRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/en/articles/': typeof EnArticlesIndexRoute
  '/en/kairon/vs/notion': typeof EnKaironVsNotionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aliados-etw-2026': typeof AliadosEtw2026Route
  '/apoya-el-lanzamiento': typeof ApoyaElLanzamientoRoute
  '/bloqueos': typeof BloqueosRoute
  '/contacto': typeof ContactoRoute
  '/diagnostico-friccion-ejecutiva': typeof DiagnosticoFriccionEjecutivaRoute
  '/enterprise': typeof EnterpriseRoute
  '/g-frame': typeof GFrameRoute
  '/g-struct': typeof GStructRoute
  '/indice-friccion': typeof IndiceFriccionRoute
  '/inversores': typeof InversoresRoute
  '/kairon': typeof KaironRoute
  '/login': typeof LoginRoute
  '/metodo-iro': typeof MetodoIroRoute
  '/newsletter': typeof NewsletterRoute
  '/politicas-legales': typeof PoliticasLegalesRoute
  '/precios': typeof PreciosRoute
  '/reestructura-1-1': typeof Reestructura11Route
  '/sobre-guillermo': typeof SobreGuillermoRoute
  '/teams': typeof TeamsRoute
  '/unete-al-equipo': typeof UneteAlEquipoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vip-pass': typeof VipPassRoute
  '/vs-ia-generativa': typeof VsIaGenerativaRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/en/about-guillermo': typeof EnAboutGuillermoRoute
  '/en/contact': typeof EnContactRoute
  '/en/enterprise': typeof EnEnterpriseRoute
  '/en/etw-2026-partners': typeof EnEtw2026PartnersRoute
  '/en/execution-blocks': typeof EnExecutionBlocksRoute
  '/en/friction-index': typeof EnFrictionIndexRoute
  '/en/g-frame': typeof EnGFrameRoute
  '/en/g-struct': typeof EnGStructRoute
  '/en/investors': typeof EnInvestorsRoute
  '/en/iro-method': typeof EnIroMethodRoute
  '/en/join-the-team': typeof EnJoinTheTeamRoute
  '/en/kairon': typeof EnKaironRoute
  '/en/newsletter': typeof EnNewsletterRoute
  '/en/pricing': typeof EnPricingRoute
  '/en/restructure-1-1': typeof EnRestructure11Route
  '/en/support-the-launch': typeof EnSupportTheLaunchRoute
  '/en/vip-pass': typeof EnVipPassRoute
  '/en/vs-generative-ai': typeof EnVsGenerativeAiRoute
  '/legal/politica-de-privacidad': typeof LegalPoliticaDePrivacidadRoute
  '/legal/politica-de-reembolsos': typeof LegalPoliticaDeReembolsosRoute
  '/legal/terminos-y-condiciones': typeof LegalTerminosYCondicionesRoute
  '/mockup/corporate-home': typeof MockupCorporateHomeRoute
  '/mockup/kairon-hero': typeof MockupKaironHeroRoute
  '/articulos': typeof ArticulosIndexRoute
  '/en': typeof EnIndexRoute
  '/admin/comentarios': typeof AdminAdminComentariosRoute
  '/admin/diagnosticos': typeof AdminAdminDiagnosticosRoute
  '/admin/reservas': typeof AdminAdminReservasRoute
  '/admin/supporters': typeof AdminAdminSupportersRoute
  '/admin/waitlist': typeof AdminAdminWaitlistRoute
  '/api/public/article-comments': typeof ApiPublicArticleCommentsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/diagnostico-submit': typeof ApiPublicDiagnosticoSubmitRoute
  '/api/public/gstruct-waitlist': typeof ApiPublicGstructWaitlistRoute
  '/api/public/gstruct-waitlist-count': typeof ApiPublicGstructWaitlistCountRoute
  '/api/public/newsletter-subscribe': typeof ApiPublicNewsletterSubscribeRoute
  '/api/public/paypal-support-capture-order': typeof ApiPublicPaypalSupportCaptureOrderRoute
  '/api/public/paypal-support-config': typeof ApiPublicPaypalSupportConfigRoute
  '/api/public/paypal-support-create-order': typeof ApiPublicPaypalSupportCreateOrderRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/en/legal/privacy-policy': typeof EnLegalPrivacyPolicyRoute
  '/en/legal/refund-policy': typeof EnLegalRefundPolicyRoute
  '/en/legal/terms-and-conditions': typeof EnLegalTermsAndConditionsRoute
  '/kairon/vs/notion': typeof KaironVsNotionRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AdminAdminIndexRoute
  '/en/articles': typeof EnArticlesIndexRoute
  '/en/kairon/vs/notion': typeof EnKaironVsNotionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/aliados-etw-2026': typeof AliadosEtw2026Route
  '/apoya-el-lanzamiento': typeof ApoyaElLanzamientoRoute
  '/articulos': typeof ArticulosRouteWithChildren
  '/bloqueos': typeof BloqueosRoute
  '/contacto': typeof ContactoRoute
  '/diagnostico-friccion-ejecutiva': typeof DiagnosticoFriccionEjecutivaRoute
  '/enterprise': typeof EnterpriseRoute
  '/g-frame': typeof GFrameRoute
  '/g-struct': typeof GStructRoute
  '/indice-friccion': typeof IndiceFriccionRoute
  '/inversores': typeof InversoresRoute
  '/kairon': typeof KaironRoute
  '/login': typeof LoginRoute
  '/metodo-iro': typeof MetodoIroRoute
  '/newsletter': typeof NewsletterRoute
  '/politicas-legales': typeof PoliticasLegalesRoute
  '/precios': typeof PreciosRoute
  '/reestructura-1-1': typeof Reestructura11Route
  '/sobre-guillermo': typeof SobreGuillermoRoute
  '/teams': typeof TeamsRoute
  '/unete-al-equipo': typeof UneteAlEquipoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/vip-pass': typeof VipPassRoute
  '/vs-ia-generativa': typeof VsIaGenerativaRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/en/about-guillermo': typeof EnAboutGuillermoRoute
  '/en/articles': typeof EnArticlesRouteWithChildren
  '/en/contact': typeof EnContactRoute
  '/en/enterprise': typeof EnEnterpriseRoute
  '/en/etw-2026-partners': typeof EnEtw2026PartnersRoute
  '/en/execution-blocks': typeof EnExecutionBlocksRoute
  '/en/friction-index': typeof EnFrictionIndexRoute
  '/en/g-frame': typeof EnGFrameRoute
  '/en/g-struct': typeof EnGStructRoute
  '/en/investors': typeof EnInvestorsRoute
  '/en/iro-method': typeof EnIroMethodRoute
  '/en/join-the-team': typeof EnJoinTheTeamRoute
  '/en/kairon': typeof EnKaironRoute
  '/en/newsletter': typeof EnNewsletterRoute
  '/en/pricing': typeof EnPricingRoute
  '/en/restructure-1-1': typeof EnRestructure11Route
  '/en/support-the-launch': typeof EnSupportTheLaunchRoute
  '/en/vip-pass': typeof EnVipPassRoute
  '/en/vs-generative-ai': typeof EnVsGenerativeAiRoute
  '/legal/politica-de-privacidad': typeof LegalPoliticaDePrivacidadRoute
  '/legal/politica-de-reembolsos': typeof LegalPoliticaDeReembolsosRoute
  '/legal/terminos-y-condiciones': typeof LegalTerminosYCondicionesRoute
  '/mockup/corporate-home': typeof MockupCorporateHomeRoute
  '/mockup/kairon-hero': typeof MockupKaironHeroRoute
  '/articulos/': typeof ArticulosIndexRoute
  '/en/': typeof EnIndexRoute
  '/_admin/admin/comentarios': typeof AdminAdminComentariosRoute
  '/_admin/admin/diagnosticos': typeof AdminAdminDiagnosticosRoute
  '/_admin/admin/reservas': typeof AdminAdminReservasRoute
  '/_admin/admin/supporters': typeof AdminAdminSupportersRoute
  '/_admin/admin/waitlist': typeof AdminAdminWaitlistRoute
  '/api/public/article-comments': typeof ApiPublicArticleCommentsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/diagnostico-submit': typeof ApiPublicDiagnosticoSubmitRoute
  '/api/public/gstruct-waitlist': typeof ApiPublicGstructWaitlistRoute
  '/api/public/gstruct-waitlist-count': typeof ApiPublicGstructWaitlistCountRoute
  '/api/public/newsletter-subscribe': typeof ApiPublicNewsletterSubscribeRoute
  '/api/public/paypal-support-capture-order': typeof ApiPublicPaypalSupportCaptureOrderRoute
  '/api/public/paypal-support-config': typeof ApiPublicPaypalSupportConfigRoute
  '/api/public/paypal-support-create-order': typeof ApiPublicPaypalSupportCreateOrderRoute
  '/en/articles/$slug': typeof EnArticlesSlugRoute
  '/en/legal/privacy-policy': typeof EnLegalPrivacyPolicyRoute
  '/en/legal/refund-policy': typeof EnLegalRefundPolicyRoute
  '/en/legal/terms-and-conditions': typeof EnLegalTermsAndConditionsRoute
  '/kairon_/vs/notion': typeof KaironVsNotionRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/en/articles/': typeof EnArticlesIndexRoute
  '/en/kairon_/vs/notion': typeof EnKaironVsNotionRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aliados-etw-2026'
    | '/apoya-el-lanzamiento'
    | '/articulos'
    | '/bloqueos'
    | '/contacto'
    | '/diagnostico-friccion-ejecutiva'
    | '/enterprise'
    | '/g-frame'
    | '/g-struct'
    | '/indice-friccion'
    | '/inversores'
    | '/kairon'
    | '/login'
    | '/metodo-iro'
    | '/newsletter'
    | '/politicas-legales'
    | '/precios'
    | '/reestructura-1-1'
    | '/sobre-guillermo'
    | '/teams'
    | '/unete-al-equipo'
    | '/unsubscribe'
    | '/vip-pass'
    | '/vs-ia-generativa'
    | '/articulos/$slug'
    | '/email/unsubscribe'
    | '/en/about-guillermo'
    | '/en/articles'
    | '/en/contact'
    | '/en/enterprise'
    | '/en/etw-2026-partners'
    | '/en/execution-blocks'
    | '/en/friction-index'
    | '/en/g-frame'
    | '/en/g-struct'
    | '/en/investors'
    | '/en/iro-method'
    | '/en/join-the-team'
    | '/en/kairon'
    | '/en/newsletter'
    | '/en/pricing'
    | '/en/restructure-1-1'
    | '/en/support-the-launch'
    | '/en/vip-pass'
    | '/en/vs-generative-ai'
    | '/legal/politica-de-privacidad'
    | '/legal/politica-de-reembolsos'
    | '/legal/terminos-y-condiciones'
    | '/mockup/corporate-home'
    | '/mockup/kairon-hero'
    | '/articulos/'
    | '/en/'
    | '/admin/comentarios'
    | '/admin/diagnosticos'
    | '/admin/reservas'
    | '/admin/supporters'
    | '/admin/waitlist'
    | '/api/public/article-comments'
    | '/api/public/contact'
    | '/api/public/diagnostico-submit'
    | '/api/public/gstruct-waitlist'
    | '/api/public/gstruct-waitlist-count'
    | '/api/public/newsletter-subscribe'
    | '/api/public/paypal-support-capture-order'
    | '/api/public/paypal-support-config'
    | '/api/public/paypal-support-create-order'
    | '/en/articles/$slug'
    | '/en/legal/privacy-policy'
    | '/en/legal/refund-policy'
    | '/en/legal/terms-and-conditions'
    | '/kairon/vs/notion'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/en/articles/'
    | '/en/kairon/vs/notion'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aliados-etw-2026'
    | '/apoya-el-lanzamiento'
    | '/bloqueos'
    | '/contacto'
    | '/diagnostico-friccion-ejecutiva'
    | '/enterprise'
    | '/g-frame'
    | '/g-struct'
    | '/indice-friccion'
    | '/inversores'
    | '/kairon'
    | '/login'
    | '/metodo-iro'
    | '/newsletter'
    | '/politicas-legales'
    | '/precios'
    | '/reestructura-1-1'
    | '/sobre-guillermo'
    | '/teams'
    | '/unete-al-equipo'
    | '/unsubscribe'
    | '/vip-pass'
    | '/vs-ia-generativa'
    | '/articulos/$slug'
    | '/email/unsubscribe'
    | '/en/about-guillermo'
    | '/en/contact'
    | '/en/enterprise'
    | '/en/etw-2026-partners'
    | '/en/execution-blocks'
    | '/en/friction-index'
    | '/en/g-frame'
    | '/en/g-struct'
    | '/en/investors'
    | '/en/iro-method'
    | '/en/join-the-team'
    | '/en/kairon'
    | '/en/newsletter'
    | '/en/pricing'
    | '/en/restructure-1-1'
    | '/en/support-the-launch'
    | '/en/vip-pass'
    | '/en/vs-generative-ai'
    | '/legal/politica-de-privacidad'
    | '/legal/politica-de-reembolsos'
    | '/legal/terminos-y-condiciones'
    | '/mockup/corporate-home'
    | '/mockup/kairon-hero'
    | '/articulos'
    | '/en'
    | '/admin/comentarios'
    | '/admin/diagnosticos'
    | '/admin/reservas'
    | '/admin/supporters'
    | '/admin/waitlist'
    | '/api/public/article-comments'
    | '/api/public/contact'
    | '/api/public/diagnostico-submit'
    | '/api/public/gstruct-waitlist'
    | '/api/public/gstruct-waitlist-count'
    | '/api/public/newsletter-subscribe'
    | '/api/public/paypal-support-capture-order'
    | '/api/public/paypal-support-config'
    | '/api/public/paypal-support-create-order'
    | '/en/articles/$slug'
    | '/en/legal/privacy-policy'
    | '/en/legal/refund-policy'
    | '/en/legal/terms-and-conditions'
    | '/kairon/vs/notion'
    | '/lovable/email/suppression'
    | '/admin'
    | '/en/articles'
    | '/en/kairon/vs/notion'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/aliados-etw-2026'
    | '/apoya-el-lanzamiento'
    | '/articulos'
    | '/bloqueos'
    | '/contacto'
    | '/diagnostico-friccion-ejecutiva'
    | '/enterprise'
    | '/g-frame'
    | '/g-struct'
    | '/indice-friccion'
    | '/inversores'
    | '/kairon'
    | '/login'
    | '/metodo-iro'
    | '/newsletter'
    | '/politicas-legales'
    | '/precios'
    | '/reestructura-1-1'
    | '/sobre-guillermo'
    | '/teams'
    | '/unete-al-equipo'
    | '/unsubscribe'
    | '/vip-pass'
    | '/vs-ia-generativa'
    | '/articulos/$slug'
    | '/email/unsubscribe'
    | '/en/about-guillermo'
    | '/en/articles'
    | '/en/contact'
    | '/en/enterprise'
    | '/en/etw-2026-partners'
    | '/en/execution-blocks'
    | '/en/friction-index'
    | '/en/g-frame'
    | '/en/g-struct'
    | '/en/investors'
    | '/en/iro-method'
    | '/en/join-the-team'
    | '/en/kairon'
    | '/en/newsletter'
    | '/en/pricing'
    | '/en/restructure-1-1'
    | '/en/support-the-launch'
    | '/en/vip-pass'
    | '/en/vs-generative-ai'
    | '/legal/politica-de-privacidad'
    | '/legal/politica-de-reembolsos'
    | '/legal/terminos-y-condiciones'
    | '/mockup/corporate-home'
    | '/mockup/kairon-hero'
    | '/articulos/'
    | '/en/'
    | '/_admin/admin/comentarios'
    | '/_admin/admin/diagnosticos'
    | '/_admin/admin/reservas'
    | '/_admin/admin/supporters'
    | '/_admin/admin/waitlist'
    | '/api/public/article-comments'
    | '/api/public/contact'
    | '/api/public/diagnostico-submit'
    | '/api/public/gstruct-waitlist'
    | '/api/public/gstruct-waitlist-count'
    | '/api/public/newsletter-subscribe'
    | '/api/public/paypal-support-capture-order'
    | '/api/public/paypal-support-config'
    | '/api/public/paypal-support-create-order'
    | '/en/articles/$slug'
    | '/en/legal/privacy-policy'
    | '/en/legal/refund-policy'
    | '/en/legal/terms-and-conditions'
    | '/kairon_/vs/notion'
    | '/lovable/email/suppression'
    | '/_admin/admin/'
    | '/en/articles/'
    | '/en/kairon_/vs/notion'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AliadosEtw2026Route: typeof AliadosEtw2026Route
  ApoyaElLanzamientoRoute: typeof ApoyaElLanzamientoRoute
  ArticulosRoute: typeof ArticulosRouteWithChildren
  BloqueosRoute: typeof BloqueosRoute
  ContactoRoute: typeof ContactoRoute
  DiagnosticoFriccionEjecutivaRoute: typeof DiagnosticoFriccionEjecutivaRoute
  EnterpriseRoute: typeof EnterpriseRoute
  GFrameRoute: typeof GFrameRoute
  GStructRoute: typeof GStructRoute
  IndiceFriccionRoute: typeof IndiceFriccionRoute
  InversoresRoute: typeof InversoresRoute
  KaironRoute: typeof KaironRoute
  LoginRoute: typeof LoginRoute
  MetodoIroRoute: typeof MetodoIroRoute
  NewsletterRoute: typeof NewsletterRoute
  PoliticasLegalesRoute: typeof PoliticasLegalesRoute
  PreciosRoute: typeof PreciosRoute
  Reestructura11Route: typeof Reestructura11Route
  SobreGuillermoRoute: typeof SobreGuillermoRoute
  TeamsRoute: typeof TeamsRoute
  UneteAlEquipoRoute: typeof UneteAlEquipoRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  VipPassRoute: typeof VipPassRoute
  VsIaGenerativaRoute: typeof VsIaGenerativaRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EnAboutGuillermoRoute: typeof EnAboutGuillermoRoute
  EnArticlesRoute: typeof EnArticlesRouteWithChildren
  EnContactRoute: typeof EnContactRoute
  EnEnterpriseRoute: typeof EnEnterpriseRoute
  EnEtw2026PartnersRoute: typeof EnEtw2026PartnersRoute
  EnExecutionBlocksRoute: typeof EnExecutionBlocksRoute
  EnFrictionIndexRoute: typeof EnFrictionIndexRoute
  EnGFrameRoute: typeof EnGFrameRoute
  EnGStructRoute: typeof EnGStructRoute
  EnInvestorsRoute: typeof EnInvestorsRoute
  EnIroMethodRoute: typeof EnIroMethodRoute
  EnJoinTheTeamRoute: typeof EnJoinTheTeamRoute
  EnKaironRoute: typeof EnKaironRoute
  EnNewsletterRoute: typeof EnNewsletterRoute
  EnPricingRoute: typeof EnPricingRoute
  EnRestructure11Route: typeof EnRestructure11Route
  EnSupportTheLaunchRoute: typeof EnSupportTheLaunchRoute
  EnVipPassRoute: typeof EnVipPassRoute
  EnVsGenerativeAiRoute: typeof EnVsGenerativeAiRoute
  LegalPoliticaDePrivacidadRoute: typeof LegalPoliticaDePrivacidadRoute
  LegalPoliticaDeReembolsosRoute: typeof LegalPoliticaDeReembolsosRoute
  LegalTerminosYCondicionesRoute: typeof LegalTerminosYCondicionesRoute
  MockupCorporateHomeRoute: typeof MockupCorporateHomeRoute
  MockupKaironHeroRoute: typeof MockupKaironHeroRoute
  EnIndexRoute: typeof EnIndexRoute
  ApiPublicArticleCommentsRoute: typeof ApiPublicArticleCommentsRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicDiagnosticoSubmitRoute: typeof ApiPublicDiagnosticoSubmitRoute
  ApiPublicGstructWaitlistRoute: typeof ApiPublicGstructWaitlistRoute
  ApiPublicGstructWaitlistCountRoute: typeof ApiPublicGstructWaitlistCountRoute
  ApiPublicNewsletterSubscribeRoute: typeof ApiPublicNewsletterSubscribeRoute
  ApiPublicPaypalSupportCaptureOrderRoute: typeof ApiPublicPaypalSupportCaptureOrderRoute
  ApiPublicPaypalSupportConfigRoute: typeof ApiPublicPaypalSupportConfigRoute
  ApiPublicPaypalSupportCreateOrderRoute: typeof ApiPublicPaypalSupportCreateOrderRoute
  EnLegalPrivacyPolicyRoute: typeof EnLegalPrivacyPolicyRoute
  EnLegalRefundPolicyRoute: typeof EnLegalRefundPolicyRoute
  EnLegalTermsAndConditionsRoute: typeof EnLegalTermsAndConditionsRoute
  KaironVsNotionRoute: typeof KaironVsNotionRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  EnKaironVsNotionRoute: typeof EnKaironVsNotionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vs-ia-generativa': {
      id: '/vs-ia-generativa'
      path: '/vs-ia-generativa'
      fullPath: '/vs-ia-generativa'
      preLoaderRoute: typeof VsIaGenerativaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vip-pass': {
      id: '/vip-pass'
      path: '/vip-pass'
      fullPath: '/vip-pass'
      preLoaderRoute: typeof VipPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unete-al-equipo': {
      id: '/unete-al-equipo'
      path: '/unete-al-equipo'
      fullPath: '/unete-al-equipo'
      preLoaderRoute: typeof UneteAlEquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-guillermo': {
      id: '/sobre-guillermo'
      path: '/sobre-guillermo'
      fullPath: '/sobre-guillermo'
      preLoaderRoute: typeof SobreGuillermoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reestructura-1-1': {
      id: '/reestructura-1-1'
      path: '/reestructura-1-1'
      fullPath: '/reestructura-1-1'
      preLoaderRoute: typeof Reestructura11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/precios': {
      id: '/precios'
      path: '/precios'
      fullPath: '/precios'
      preLoaderRoute: typeof PreciosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas-legales': {
      id: '/politicas-legales'
      path: '/politicas-legales'
      fullPath: '/politicas-legales'
      preLoaderRoute: typeof PoliticasLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/newsletter': {
      id: '/newsletter'
      path: '/newsletter'
      fullPath: '/newsletter'
      preLoaderRoute: typeof NewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodo-iro': {
      id: '/metodo-iro'
      path: '/metodo-iro'
      fullPath: '/metodo-iro'
      preLoaderRoute: typeof MetodoIroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kairon': {
      id: '/kairon'
      path: '/kairon'
      fullPath: '/kairon'
      preLoaderRoute: typeof KaironRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inversores': {
      id: '/inversores'
      path: '/inversores'
      fullPath: '/inversores'
      preLoaderRoute: typeof InversoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/indice-friccion': {
      id: '/indice-friccion'
      path: '/indice-friccion'
      fullPath: '/indice-friccion'
      preLoaderRoute: typeof IndiceFriccionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g-struct': {
      id: '/g-struct'
      path: '/g-struct'
      fullPath: '/g-struct'
      preLoaderRoute: typeof GStructRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g-frame': {
      id: '/g-frame'
      path: '/g-frame'
      fullPath: '/g-frame'
      preLoaderRoute: typeof GFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico-friccion-ejecutiva': {
      id: '/diagnostico-friccion-ejecutiva'
      path: '/diagnostico-friccion-ejecutiva'
      fullPath: '/diagnostico-friccion-ejecutiva'
      preLoaderRoute: typeof DiagnosticoFriccionEjecutivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bloqueos': {
      id: '/bloqueos'
      path: '/bloqueos'
      fullPath: '/bloqueos'
      preLoaderRoute: typeof BloqueosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos': {
      id: '/articulos'
      path: '/articulos'
      fullPath: '/articulos'
      preLoaderRoute: typeof ArticulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apoya-el-lanzamiento': {
      id: '/apoya-el-lanzamiento'
      path: '/apoya-el-lanzamiento'
      fullPath: '/apoya-el-lanzamiento'
      preLoaderRoute: typeof ApoyaElLanzamientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliados-etw-2026': {
      id: '/aliados-etw-2026'
      path: '/aliados-etw-2026'
      fullPath: '/aliados-etw-2026'
      preLoaderRoute: typeof AliadosEtw2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/': {
      id: '/articulos/'
      path: '/'
      fullPath: '/articulos/'
      preLoaderRoute: typeof ArticulosIndexRouteImport
      parentRoute: typeof ArticulosRoute
    }
    '/mockup/kairon-hero': {
      id: '/mockup/kairon-hero'
      path: '/mockup/kairon-hero'
      fullPath: '/mockup/kairon-hero'
      preLoaderRoute: typeof MockupKaironHeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mockup/corporate-home': {
      id: '/mockup/corporate-home'
      path: '/mockup/corporate-home'
      fullPath: '/mockup/corporate-home'
      preLoaderRoute: typeof MockupCorporateHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terminos-y-condiciones': {
      id: '/legal/terminos-y-condiciones'
      path: '/legal/terminos-y-condiciones'
      fullPath: '/legal/terminos-y-condiciones'
      preLoaderRoute: typeof LegalTerminosYCondicionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/politica-de-reembolsos': {
      id: '/legal/politica-de-reembolsos'
      path: '/legal/politica-de-reembolsos'
      fullPath: '/legal/politica-de-reembolsos'
      preLoaderRoute: typeof LegalPoliticaDeReembolsosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/politica-de-privacidad': {
      id: '/legal/politica-de-privacidad'
      path: '/legal/politica-de-privacidad'
      fullPath: '/legal/politica-de-privacidad'
      preLoaderRoute: typeof LegalPoliticaDePrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/vs-generative-ai': {
      id: '/en/vs-generative-ai'
      path: '/en/vs-generative-ai'
      fullPath: '/en/vs-generative-ai'
      preLoaderRoute: typeof EnVsGenerativeAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/vip-pass': {
      id: '/en/vip-pass'
      path: '/en/vip-pass'
      fullPath: '/en/vip-pass'
      preLoaderRoute: typeof EnVipPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/support-the-launch': {
      id: '/en/support-the-launch'
      path: '/en/support-the-launch'
      fullPath: '/en/support-the-launch'
      preLoaderRoute: typeof EnSupportTheLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/restructure-1-1': {
      id: '/en/restructure-1-1'
      path: '/en/restructure-1-1'
      fullPath: '/en/restructure-1-1'
      preLoaderRoute: typeof EnRestructure11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/pricing': {
      id: '/en/pricing'
      path: '/en/pricing'
      fullPath: '/en/pricing'
      preLoaderRoute: typeof EnPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/newsletter': {
      id: '/en/newsletter'
      path: '/en/newsletter'
      fullPath: '/en/newsletter'
      preLoaderRoute: typeof EnNewsletterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/kairon': {
      id: '/en/kairon'
      path: '/en/kairon'
      fullPath: '/en/kairon'
      preLoaderRoute: typeof EnKaironRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/join-the-team': {
      id: '/en/join-the-team'
      path: '/en/join-the-team'
      fullPath: '/en/join-the-team'
      preLoaderRoute: typeof EnJoinTheTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/iro-method': {
      id: '/en/iro-method'
      path: '/en/iro-method'
      fullPath: '/en/iro-method'
      preLoaderRoute: typeof EnIroMethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/investors': {
      id: '/en/investors'
      path: '/en/investors'
      fullPath: '/en/investors'
      preLoaderRoute: typeof EnInvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/g-struct': {
      id: '/en/g-struct'
      path: '/en/g-struct'
      fullPath: '/en/g-struct'
      preLoaderRoute: typeof EnGStructRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/g-frame': {
      id: '/en/g-frame'
      path: '/en/g-frame'
      fullPath: '/en/g-frame'
      preLoaderRoute: typeof EnGFrameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/friction-index': {
      id: '/en/friction-index'
      path: '/en/friction-index'
      fullPath: '/en/friction-index'
      preLoaderRoute: typeof EnFrictionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/execution-blocks': {
      id: '/en/execution-blocks'
      path: '/en/execution-blocks'
      fullPath: '/en/execution-blocks'
      preLoaderRoute: typeof EnExecutionBlocksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/etw-2026-partners': {
      id: '/en/etw-2026-partners'
      path: '/en/etw-2026-partners'
      fullPath: '/en/etw-2026-partners'
      preLoaderRoute: typeof EnEtw2026PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/enterprise': {
      id: '/en/enterprise'
      path: '/en/enterprise'
      fullPath: '/en/enterprise'
      preLoaderRoute: typeof EnEnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/articles': {
      id: '/en/articles'
      path: '/en/articles'
      fullPath: '/en/articles'
      preLoaderRoute: typeof EnArticlesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about-guillermo': {
      id: '/en/about-guillermo'
      path: '/en/about-guillermo'
      fullPath: '/en/about-guillermo'
      preLoaderRoute: typeof EnAboutGuillermoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/$slug': {
      id: '/articulos/$slug'
      path: '/$slug'
      fullPath: '/articulos/$slug'
      preLoaderRoute: typeof ArticulosSlugRouteImport
      parentRoute: typeof ArticulosRoute
    }
    '/en/articles/': {
      id: '/en/articles/'
      path: '/'
      fullPath: '/en/articles/'
      preLoaderRoute: typeof EnArticlesIndexRouteImport
      parentRoute: typeof EnArticlesRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kairon_/vs/notion': {
      id: '/kairon_/vs/notion'
      path: '/kairon/vs/notion'
      fullPath: '/kairon/vs/notion'
      preLoaderRoute: typeof KaironVsNotionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/legal/terms-and-conditions': {
      id: '/en/legal/terms-and-conditions'
      path: '/en/legal/terms-and-conditions'
      fullPath: '/en/legal/terms-and-conditions'
      preLoaderRoute: typeof EnLegalTermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/legal/refund-policy': {
      id: '/en/legal/refund-policy'
      path: '/en/legal/refund-policy'
      fullPath: '/en/legal/refund-policy'
      preLoaderRoute: typeof EnLegalRefundPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/legal/privacy-policy': {
      id: '/en/legal/privacy-policy'
      path: '/en/legal/privacy-policy'
      fullPath: '/en/legal/privacy-policy'
      preLoaderRoute: typeof EnLegalPrivacyPolicyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/articles/$slug': {
      id: '/en/articles/$slug'
      path: '/$slug'
      fullPath: '/en/articles/$slug'
      preLoaderRoute: typeof EnArticlesSlugRouteImport
      parentRoute: typeof EnArticlesRoute
    }
    '/api/public/paypal-support-create-order': {
      id: '/api/public/paypal-support-create-order'
      path: '/api/public/paypal-support-create-order'
      fullPath: '/api/public/paypal-support-create-order'
      preLoaderRoute: typeof ApiPublicPaypalSupportCreateOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal-support-config': {
      id: '/api/public/paypal-support-config'
      path: '/api/public/paypal-support-config'
      fullPath: '/api/public/paypal-support-config'
      preLoaderRoute: typeof ApiPublicPaypalSupportConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/paypal-support-capture-order': {
      id: '/api/public/paypal-support-capture-order'
      path: '/api/public/paypal-support-capture-order'
      fullPath: '/api/public/paypal-support-capture-order'
      preLoaderRoute: typeof ApiPublicPaypalSupportCaptureOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/newsletter-subscribe': {
      id: '/api/public/newsletter-subscribe'
      path: '/api/public/newsletter-subscribe'
      fullPath: '/api/public/newsletter-subscribe'
      preLoaderRoute: typeof ApiPublicNewsletterSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gstruct-waitlist-count': {
      id: '/api/public/gstruct-waitlist-count'
      path: '/api/public/gstruct-waitlist-count'
      fullPath: '/api/public/gstruct-waitlist-count'
      preLoaderRoute: typeof ApiPublicGstructWaitlistCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gstruct-waitlist': {
      id: '/api/public/gstruct-waitlist'
      path: '/api/public/gstruct-waitlist'
      fullPath: '/api/public/gstruct-waitlist'
      preLoaderRoute: typeof ApiPublicGstructWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diagnostico-submit': {
      id: '/api/public/diagnostico-submit'
      path: '/api/public/diagnostico-submit'
      fullPath: '/api/public/diagnostico-submit'
      preLoaderRoute: typeof ApiPublicDiagnosticoSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/article-comments': {
      id: '/api/public/article-comments'
      path: '/api/public/article-comments'
      fullPath: '/api/public/article-comments'
      preLoaderRoute: typeof ApiPublicArticleCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/waitlist': {
      id: '/_admin/admin/waitlist'
      path: '/admin/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminAdminWaitlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/supporters': {
      id: '/_admin/admin/supporters'
      path: '/admin/supporters'
      fullPath: '/admin/supporters'
      preLoaderRoute: typeof AdminAdminSupportersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reservas': {
      id: '/_admin/admin/reservas'
      path: '/admin/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminAdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/diagnosticos': {
      id: '/_admin/admin/diagnosticos'
      path: '/admin/diagnosticos'
      fullPath: '/admin/diagnosticos'
      preLoaderRoute: typeof AdminAdminDiagnosticosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/comentarios': {
      id: '/_admin/admin/comentarios'
      path: '/admin/comentarios'
      fullPath: '/admin/comentarios'
      preLoaderRoute: typeof AdminAdminComentariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/kairon_/vs/notion': {
      id: '/en/kairon_/vs/notion'
      path: '/en/kairon/vs/notion'
      fullPath: '/en/kairon/vs/notion'
      preLoaderRoute: typeof EnKaironVsNotionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminComentariosRoute: typeof AdminAdminComentariosRoute
  AdminAdminDiagnosticosRoute: typeof AdminAdminDiagnosticosRoute
  AdminAdminReservasRoute: typeof AdminAdminReservasRoute
  AdminAdminSupportersRoute: typeof AdminAdminSupportersRoute
  AdminAdminWaitlistRoute: typeof AdminAdminWaitlistRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminComentariosRoute: AdminAdminComentariosRoute,
  AdminAdminDiagnosticosRoute: AdminAdminDiagnosticosRoute,
  AdminAdminReservasRoute: AdminAdminReservasRoute,
  AdminAdminSupportersRoute: AdminAdminSupportersRoute,
  AdminAdminWaitlistRoute: AdminAdminWaitlistRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticulosRouteChildren {
  ArticulosSlugRoute: typeof ArticulosSlugRoute
  ArticulosIndexRoute: typeof ArticulosIndexRoute
}

const ArticulosRouteChildren: ArticulosRouteChildren = {
  ArticulosSlugRoute: ArticulosSlugRoute,
  ArticulosIndexRoute: ArticulosIndexRoute,
}

const ArticulosRouteWithChildren = ArticulosRoute._addFileChildren(
  ArticulosRouteChildren,
)

interface EnArticlesRouteChildren {
  EnArticlesSlugRoute: typeof EnArticlesSlugRoute
  EnArticlesIndexRoute: typeof EnArticlesIndexRoute
}

const EnArticlesRouteChildren: EnArticlesRouteChildren = {
  EnArticlesSlugRoute: EnArticlesSlugRoute,
  EnArticlesIndexRoute: EnArticlesIndexRoute,
}

const EnArticlesRouteWithChildren = EnArticlesRoute._addFileChildren(
  EnArticlesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AliadosEtw2026Route: AliadosEtw2026Route,
  ApoyaElLanzamientoRoute: ApoyaElLanzamientoRoute,
  ArticulosRoute: ArticulosRouteWithChildren,
  BloqueosRoute: BloqueosRoute,
  ContactoRoute: ContactoRoute,
  DiagnosticoFriccionEjecutivaRoute: DiagnosticoFriccionEjecutivaRoute,
  EnterpriseRoute: EnterpriseRoute,
  GFrameRoute: GFrameRoute,
  GStructRoute: GStructRoute,
  IndiceFriccionRoute: IndiceFriccionRoute,
  InversoresRoute: InversoresRoute,
  KaironRoute: KaironRoute,
  LoginRoute: LoginRoute,
  MetodoIroRoute: MetodoIroRoute,
  NewsletterRoute: NewsletterRoute,
  PoliticasLegalesRoute: PoliticasLegalesRoute,
  PreciosRoute: PreciosRoute,
  Reestructura11Route: Reestructura11Route,
  SobreGuillermoRoute: SobreGuillermoRoute,
  TeamsRoute: TeamsRoute,
  UneteAlEquipoRoute: UneteAlEquipoRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  VipPassRoute: VipPassRoute,
  VsIaGenerativaRoute: VsIaGenerativaRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EnAboutGuillermoRoute: EnAboutGuillermoRoute,
  EnArticlesRoute: EnArticlesRouteWithChildren,
  EnContactRoute: EnContactRoute,
  EnEnterpriseRoute: EnEnterpriseRoute,
  EnEtw2026PartnersRoute: EnEtw2026PartnersRoute,
  EnExecutionBlocksRoute: EnExecutionBlocksRoute,
  EnFrictionIndexRoute: EnFrictionIndexRoute,
  EnGFrameRoute: EnGFrameRoute,
  EnGStructRoute: EnGStructRoute,
  EnInvestorsRoute: EnInvestorsRoute,
  EnIroMethodRoute: EnIroMethodRoute,
  EnJoinTheTeamRoute: EnJoinTheTeamRoute,
  EnKaironRoute: EnKaironRoute,
  EnNewsletterRoute: EnNewsletterRoute,
  EnPricingRoute: EnPricingRoute,
  EnRestructure11Route: EnRestructure11Route,
  EnSupportTheLaunchRoute: EnSupportTheLaunchRoute,
  EnVipPassRoute: EnVipPassRoute,
  EnVsGenerativeAiRoute: EnVsGenerativeAiRoute,
  LegalPoliticaDePrivacidadRoute: LegalPoliticaDePrivacidadRoute,
  LegalPoliticaDeReembolsosRoute: LegalPoliticaDeReembolsosRoute,
  LegalTerminosYCondicionesRoute: LegalTerminosYCondicionesRoute,
  MockupCorporateHomeRoute: MockupCorporateHomeRoute,
  MockupKaironHeroRoute: MockupKaironHeroRoute,
  EnIndexRoute: EnIndexRoute,
  ApiPublicArticleCommentsRoute: ApiPublicArticleCommentsRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicDiagnosticoSubmitRoute: ApiPublicDiagnosticoSubmitRoute,
  ApiPublicGstructWaitlistRoute: ApiPublicGstructWaitlistRoute,
  ApiPublicGstructWaitlistCountRoute: ApiPublicGstructWaitlistCountRoute,
  ApiPublicNewsletterSubscribeRoute: ApiPublicNewsletterSubscribeRoute,
  ApiPublicPaypalSupportCaptureOrderRoute:
    ApiPublicPaypalSupportCaptureOrderRoute,
  ApiPublicPaypalSupportConfigRoute: ApiPublicPaypalSupportConfigRoute,
  ApiPublicPaypalSupportCreateOrderRoute:
    ApiPublicPaypalSupportCreateOrderRoute,
  EnLegalPrivacyPolicyRoute: EnLegalPrivacyPolicyRoute,
  EnLegalRefundPolicyRoute: EnLegalRefundPolicyRoute,
  EnLegalTermsAndConditionsRoute: EnLegalTermsAndConditionsRoute,
  KaironVsNotionRoute: KaironVsNotionRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  EnKaironVsNotionRoute: EnKaironVsNotionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
