/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as UneteAlEquipoRouteImport } from './routes/unete-al-equipo'
import { Route as SobreGuillermoRouteImport } from './routes/sobre-guillermo'
import { Route as Reestructura11RouteImport } from './routes/reestructura-1-1'
import { Route as PoliticasLegalesRouteImport } from './routes/politicas-legales'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InversoresRouteImport } from './routes/inversores'
import { Route as GStructRouteImport } from './routes/g-struct'
import { Route as EnterpriseRouteImport } from './routes/enterprise'
import { Route as DiagnosticoFriccionEjecutivaRouteImport } from './routes/diagnostico-friccion-ejecutiva'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as ArticulosRouteImport } from './routes/articulos'
import { Route as AliadosEtw2026RouteImport } from './routes/aliados-etw-2026'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en.index'
import { Route as ArticulosIndexRouteImport } from './routes/articulos.index'
import { Route as EnRestructure11RouteImport } from './routes/en.restructure-1-1'
import { Route as EnJoinTheTeamRouteImport } from './routes/en.join-the-team'
import { Route as EnInvestorsRouteImport } from './routes/en.investors'
import { Route as EnGStructRouteImport } from './routes/en.g-struct'
import { Route as EnEtw2026PartnersRouteImport } from './routes/en.etw-2026-partners'
import { Route as EnEnterpriseRouteImport } from './routes/en.enterprise'
import { Route as EnContactRouteImport } from './routes/en.contact'
import { Route as EnAboutGuillermoRouteImport } from './routes/en.about-guillermo'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as ArticulosSlugRouteImport } from './routes/articulos.$slug'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin.index'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiPublicGstructWaitlistCountRouteImport } from './routes/api/public/gstruct-waitlist-count'
import { Route as ApiPublicGstructWaitlistRouteImport } from './routes/api/public/gstruct-waitlist'
import { Route as ApiPublicDiagnosticoSubmitRouteImport } from './routes/api/public/diagnostico-submit'
import { Route as ApiPublicContactRouteImport } from './routes/api/public/contact'
import { Route as ApiPublicArticleCommentsRouteImport } from './routes/api/public/article-comments'
import { Route as AdminAdminWaitlistRouteImport } from './routes/_admin/admin.waitlist'
import { Route as AdminAdminReservasRouteImport } from './routes/_admin/admin.reservas'
import { Route as AdminAdminDiagnosticosRouteImport } from './routes/_admin/admin.diagnosticos'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const UneteAlEquipoRoute = UneteAlEquipoRouteImport.update({
  id: '/unete-al-equipo',
  path: '/unete-al-equipo',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreGuillermoRoute = SobreGuillermoRouteImport.update({
  id: '/sobre-guillermo',
  path: '/sobre-guillermo',
  getParentRoute: () => rootRouteImport,
} as any)
const Reestructura11Route = Reestructura11RouteImport.update({
  id: '/reestructura-1-1',
  path: '/reestructura-1-1',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticasLegalesRoute = PoliticasLegalesRouteImport.update({
  id: '/politicas-legales',
  path: '/politicas-legales',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InversoresRoute = InversoresRouteImport.update({
  id: '/inversores',
  path: '/inversores',
  getParentRoute: () => rootRouteImport,
} as any)
const GStructRoute = GStructRouteImport.update({
  id: '/g-struct',
  path: '/g-struct',
  getParentRoute: () => rootRouteImport,
} as any)
const EnterpriseRoute = EnterpriseRouteImport.update({
  id: '/enterprise',
  path: '/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoFriccionEjecutivaRoute =
  DiagnosticoFriccionEjecutivaRouteImport.update({
    id: '/diagnostico-friccion-ejecutiva',
    path: '/diagnostico-friccion-ejecutiva',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosRoute = ArticulosRouteImport.update({
  id: '/articulos',
  path: '/articulos',
  getParentRoute: () => rootRouteImport,
} as any)
const AliadosEtw2026Route = AliadosEtw2026RouteImport.update({
  id: '/aliados-etw-2026',
  path: '/aliados-etw-2026',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosIndexRoute = ArticulosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ArticulosRoute,
} as any)
const EnRestructure11Route = EnRestructure11RouteImport.update({
  id: '/en/restructure-1-1',
  path: '/en/restructure-1-1',
  getParentRoute: () => rootRouteImport,
} as any)
const EnJoinTheTeamRoute = EnJoinTheTeamRouteImport.update({
  id: '/en/join-the-team',
  path: '/en/join-the-team',
  getParentRoute: () => rootRouteImport,
} as any)
const EnInvestorsRoute = EnInvestorsRouteImport.update({
  id: '/en/investors',
  path: '/en/investors',
  getParentRoute: () => rootRouteImport,
} as any)
const EnGStructRoute = EnGStructRouteImport.update({
  id: '/en/g-struct',
  path: '/en/g-struct',
  getParentRoute: () => rootRouteImport,
} as any)
const EnEtw2026PartnersRoute = EnEtw2026PartnersRouteImport.update({
  id: '/en/etw-2026-partners',
  path: '/en/etw-2026-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const EnEnterpriseRoute = EnEnterpriseRouteImport.update({
  id: '/en/enterprise',
  path: '/en/enterprise',
  getParentRoute: () => rootRouteImport,
} as any)
const EnContactRoute = EnContactRouteImport.update({
  id: '/en/contact',
  path: '/en/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const EnAboutGuillermoRoute = EnAboutGuillermoRouteImport.update({
  id: '/en/about-guillermo',
  path: '/en/about-guillermo',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ArticulosSlugRoute = ArticulosSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ArticulosRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGstructWaitlistCountRoute =
  ApiPublicGstructWaitlistCountRouteImport.update({
    id: '/api/public/gstruct-waitlist-count',
    path: '/api/public/gstruct-waitlist-count',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicGstructWaitlistRoute =
  ApiPublicGstructWaitlistRouteImport.update({
    id: '/api/public/gstruct-waitlist',
    path: '/api/public/gstruct-waitlist',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDiagnosticoSubmitRoute =
  ApiPublicDiagnosticoSubmitRouteImport.update({
    id: '/api/public/diagnostico-submit',
    path: '/api/public/diagnostico-submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicContactRoute = ApiPublicContactRouteImport.update({
  id: '/api/public/contact',
  path: '/api/public/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicArticleCommentsRoute =
  ApiPublicArticleCommentsRouteImport.update({
    id: '/api/public/article-comments',
    path: '/api/public/article-comments',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminAdminWaitlistRoute = AdminAdminWaitlistRouteImport.update({
  id: '/admin/waitlist',
  path: '/admin/waitlist',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminReservasRoute = AdminAdminReservasRouteImport.update({
  id: '/admin/reservas',
  path: '/admin/reservas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminDiagnosticosRoute = AdminAdminDiagnosticosRouteImport.update({
  id: '/admin/diagnosticos',
  path: '/admin/diagnosticos',
  getParentRoute: () => AdminRoute,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aliados-etw-2026': typeof AliadosEtw2026Route
  '/articulos': typeof ArticulosRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/diagnostico-friccion-ejecutiva': typeof DiagnosticoFriccionEjecutivaRoute
  '/enterprise': typeof EnterpriseRoute
  '/g-struct': typeof GStructRoute
  '/inversores': typeof InversoresRoute
  '/login': typeof LoginRoute
  '/politicas-legales': typeof PoliticasLegalesRoute
  '/reestructura-1-1': typeof Reestructura11Route
  '/sobre-guillermo': typeof SobreGuillermoRoute
  '/unete-al-equipo': typeof UneteAlEquipoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/en/about-guillermo': typeof EnAboutGuillermoRoute
  '/en/contact': typeof EnContactRoute
  '/en/enterprise': typeof EnEnterpriseRoute
  '/en/etw-2026-partners': typeof EnEtw2026PartnersRoute
  '/en/g-struct': typeof EnGStructRoute
  '/en/investors': typeof EnInvestorsRoute
  '/en/join-the-team': typeof EnJoinTheTeamRoute
  '/en/restructure-1-1': typeof EnRestructure11Route
  '/articulos/': typeof ArticulosIndexRoute
  '/en/': typeof EnIndexRoute
  '/admin/diagnosticos': typeof AdminAdminDiagnosticosRoute
  '/admin/reservas': typeof AdminAdminReservasRoute
  '/admin/waitlist': typeof AdminAdminWaitlistRoute
  '/api/public/article-comments': typeof ApiPublicArticleCommentsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/diagnostico-submit': typeof ApiPublicDiagnosticoSubmitRoute
  '/api/public/gstruct-waitlist': typeof ApiPublicGstructWaitlistRoute
  '/api/public/gstruct-waitlist-count': typeof ApiPublicGstructWaitlistCountRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aliados-etw-2026': typeof AliadosEtw2026Route
  '/contacto': typeof ContactoRoute
  '/diagnostico-friccion-ejecutiva': typeof DiagnosticoFriccionEjecutivaRoute
  '/enterprise': typeof EnterpriseRoute
  '/g-struct': typeof GStructRoute
  '/inversores': typeof InversoresRoute
  '/login': typeof LoginRoute
  '/politicas-legales': typeof PoliticasLegalesRoute
  '/reestructura-1-1': typeof Reestructura11Route
  '/sobre-guillermo': typeof SobreGuillermoRoute
  '/unete-al-equipo': typeof UneteAlEquipoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/en/about-guillermo': typeof EnAboutGuillermoRoute
  '/en/contact': typeof EnContactRoute
  '/en/enterprise': typeof EnEnterpriseRoute
  '/en/etw-2026-partners': typeof EnEtw2026PartnersRoute
  '/en/g-struct': typeof EnGStructRoute
  '/en/investors': typeof EnInvestorsRoute
  '/en/join-the-team': typeof EnJoinTheTeamRoute
  '/en/restructure-1-1': typeof EnRestructure11Route
  '/articulos': typeof ArticulosIndexRoute
  '/en': typeof EnIndexRoute
  '/admin/diagnosticos': typeof AdminAdminDiagnosticosRoute
  '/admin/reservas': typeof AdminAdminReservasRoute
  '/admin/waitlist': typeof AdminAdminWaitlistRoute
  '/api/public/article-comments': typeof ApiPublicArticleCommentsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/diagnostico-submit': typeof ApiPublicDiagnosticoSubmitRoute
  '/api/public/gstruct-waitlist': typeof ApiPublicGstructWaitlistRoute
  '/api/public/gstruct-waitlist-count': typeof ApiPublicGstructWaitlistCountRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/admin': typeof AdminAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/aliados-etw-2026': typeof AliadosEtw2026Route
  '/articulos': typeof ArticulosRouteWithChildren
  '/contacto': typeof ContactoRoute
  '/diagnostico-friccion-ejecutiva': typeof DiagnosticoFriccionEjecutivaRoute
  '/enterprise': typeof EnterpriseRoute
  '/g-struct': typeof GStructRoute
  '/inversores': typeof InversoresRoute
  '/login': typeof LoginRoute
  '/politicas-legales': typeof PoliticasLegalesRoute
  '/reestructura-1-1': typeof Reestructura11Route
  '/sobre-guillermo': typeof SobreGuillermoRoute
  '/unete-al-equipo': typeof UneteAlEquipoRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/articulos/$slug': typeof ArticulosSlugRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/en/about-guillermo': typeof EnAboutGuillermoRoute
  '/en/contact': typeof EnContactRoute
  '/en/enterprise': typeof EnEnterpriseRoute
  '/en/etw-2026-partners': typeof EnEtw2026PartnersRoute
  '/en/g-struct': typeof EnGStructRoute
  '/en/investors': typeof EnInvestorsRoute
  '/en/join-the-team': typeof EnJoinTheTeamRoute
  '/en/restructure-1-1': typeof EnRestructure11Route
  '/articulos/': typeof ArticulosIndexRoute
  '/en/': typeof EnIndexRoute
  '/_admin/admin/diagnosticos': typeof AdminAdminDiagnosticosRoute
  '/_admin/admin/reservas': typeof AdminAdminReservasRoute
  '/_admin/admin/waitlist': typeof AdminAdminWaitlistRoute
  '/api/public/article-comments': typeof ApiPublicArticleCommentsRoute
  '/api/public/contact': typeof ApiPublicContactRoute
  '/api/public/diagnostico-submit': typeof ApiPublicDiagnosticoSubmitRoute
  '/api/public/gstruct-waitlist': typeof ApiPublicGstructWaitlistRoute
  '/api/public/gstruct-waitlist-count': typeof ApiPublicGstructWaitlistCountRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aliados-etw-2026'
    | '/articulos'
    | '/contacto'
    | '/diagnostico-friccion-ejecutiva'
    | '/enterprise'
    | '/g-struct'
    | '/inversores'
    | '/login'
    | '/politicas-legales'
    | '/reestructura-1-1'
    | '/sobre-guillermo'
    | '/unete-al-equipo'
    | '/unsubscribe'
    | '/articulos/$slug'
    | '/email/unsubscribe'
    | '/en/about-guillermo'
    | '/en/contact'
    | '/en/enterprise'
    | '/en/etw-2026-partners'
    | '/en/g-struct'
    | '/en/investors'
    | '/en/join-the-team'
    | '/en/restructure-1-1'
    | '/articulos/'
    | '/en/'
    | '/admin/diagnosticos'
    | '/admin/reservas'
    | '/admin/waitlist'
    | '/api/public/article-comments'
    | '/api/public/contact'
    | '/api/public/diagnostico-submit'
    | '/api/public/gstruct-waitlist'
    | '/api/public/gstruct-waitlist-count'
    | '/lovable/email/suppression'
    | '/admin/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aliados-etw-2026'
    | '/contacto'
    | '/diagnostico-friccion-ejecutiva'
    | '/enterprise'
    | '/g-struct'
    | '/inversores'
    | '/login'
    | '/politicas-legales'
    | '/reestructura-1-1'
    | '/sobre-guillermo'
    | '/unete-al-equipo'
    | '/unsubscribe'
    | '/articulos/$slug'
    | '/email/unsubscribe'
    | '/en/about-guillermo'
    | '/en/contact'
    | '/en/enterprise'
    | '/en/etw-2026-partners'
    | '/en/g-struct'
    | '/en/investors'
    | '/en/join-the-team'
    | '/en/restructure-1-1'
    | '/articulos'
    | '/en'
    | '/admin/diagnosticos'
    | '/admin/reservas'
    | '/admin/waitlist'
    | '/api/public/article-comments'
    | '/api/public/contact'
    | '/api/public/diagnostico-submit'
    | '/api/public/gstruct-waitlist'
    | '/api/public/gstruct-waitlist-count'
    | '/lovable/email/suppression'
    | '/admin'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/aliados-etw-2026'
    | '/articulos'
    | '/contacto'
    | '/diagnostico-friccion-ejecutiva'
    | '/enterprise'
    | '/g-struct'
    | '/inversores'
    | '/login'
    | '/politicas-legales'
    | '/reestructura-1-1'
    | '/sobre-guillermo'
    | '/unete-al-equipo'
    | '/unsubscribe'
    | '/articulos/$slug'
    | '/email/unsubscribe'
    | '/en/about-guillermo'
    | '/en/contact'
    | '/en/enterprise'
    | '/en/etw-2026-partners'
    | '/en/g-struct'
    | '/en/investors'
    | '/en/join-the-team'
    | '/en/restructure-1-1'
    | '/articulos/'
    | '/en/'
    | '/_admin/admin/diagnosticos'
    | '/_admin/admin/reservas'
    | '/_admin/admin/waitlist'
    | '/api/public/article-comments'
    | '/api/public/contact'
    | '/api/public/diagnostico-submit'
    | '/api/public/gstruct-waitlist'
    | '/api/public/gstruct-waitlist-count'
    | '/lovable/email/suppression'
    | '/_admin/admin/'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AliadosEtw2026Route: typeof AliadosEtw2026Route
  ArticulosRoute: typeof ArticulosRouteWithChildren
  ContactoRoute: typeof ContactoRoute
  DiagnosticoFriccionEjecutivaRoute: typeof DiagnosticoFriccionEjecutivaRoute
  EnterpriseRoute: typeof EnterpriseRoute
  GStructRoute: typeof GStructRoute
  InversoresRoute: typeof InversoresRoute
  LoginRoute: typeof LoginRoute
  PoliticasLegalesRoute: typeof PoliticasLegalesRoute
  Reestructura11Route: typeof Reestructura11Route
  SobreGuillermoRoute: typeof SobreGuillermoRoute
  UneteAlEquipoRoute: typeof UneteAlEquipoRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  EnAboutGuillermoRoute: typeof EnAboutGuillermoRoute
  EnContactRoute: typeof EnContactRoute
  EnEnterpriseRoute: typeof EnEnterpriseRoute
  EnEtw2026PartnersRoute: typeof EnEtw2026PartnersRoute
  EnGStructRoute: typeof EnGStructRoute
  EnInvestorsRoute: typeof EnInvestorsRoute
  EnJoinTheTeamRoute: typeof EnJoinTheTeamRoute
  EnRestructure11Route: typeof EnRestructure11Route
  EnIndexRoute: typeof EnIndexRoute
  ApiPublicArticleCommentsRoute: typeof ApiPublicArticleCommentsRoute
  ApiPublicContactRoute: typeof ApiPublicContactRoute
  ApiPublicDiagnosticoSubmitRoute: typeof ApiPublicDiagnosticoSubmitRoute
  ApiPublicGstructWaitlistRoute: typeof ApiPublicGstructWaitlistRoute
  ApiPublicGstructWaitlistCountRoute: typeof ApiPublicGstructWaitlistCountRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unete-al-equipo': {
      id: '/unete-al-equipo'
      path: '/unete-al-equipo'
      fullPath: '/unete-al-equipo'
      preLoaderRoute: typeof UneteAlEquipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-guillermo': {
      id: '/sobre-guillermo'
      path: '/sobre-guillermo'
      fullPath: '/sobre-guillermo'
      preLoaderRoute: typeof SobreGuillermoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reestructura-1-1': {
      id: '/reestructura-1-1'
      path: '/reestructura-1-1'
      fullPath: '/reestructura-1-1'
      preLoaderRoute: typeof Reestructura11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politicas-legales': {
      id: '/politicas-legales'
      path: '/politicas-legales'
      fullPath: '/politicas-legales'
      preLoaderRoute: typeof PoliticasLegalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inversores': {
      id: '/inversores'
      path: '/inversores'
      fullPath: '/inversores'
      preLoaderRoute: typeof InversoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/g-struct': {
      id: '/g-struct'
      path: '/g-struct'
      fullPath: '/g-struct'
      preLoaderRoute: typeof GStructRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enterprise': {
      id: '/enterprise'
      path: '/enterprise'
      fullPath: '/enterprise'
      preLoaderRoute: typeof EnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico-friccion-ejecutiva': {
      id: '/diagnostico-friccion-ejecutiva'
      path: '/diagnostico-friccion-ejecutiva'
      fullPath: '/diagnostico-friccion-ejecutiva'
      preLoaderRoute: typeof DiagnosticoFriccionEjecutivaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos': {
      id: '/articulos'
      path: '/articulos'
      fullPath: '/articulos'
      preLoaderRoute: typeof ArticulosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aliados-etw-2026': {
      id: '/aliados-etw-2026'
      path: '/aliados-etw-2026'
      fullPath: '/aliados-etw-2026'
      preLoaderRoute: typeof AliadosEtw2026RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/': {
      id: '/articulos/'
      path: '/'
      fullPath: '/articulos/'
      preLoaderRoute: typeof ArticulosIndexRouteImport
      parentRoute: typeof ArticulosRoute
    }
    '/en/restructure-1-1': {
      id: '/en/restructure-1-1'
      path: '/en/restructure-1-1'
      fullPath: '/en/restructure-1-1'
      preLoaderRoute: typeof EnRestructure11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/join-the-team': {
      id: '/en/join-the-team'
      path: '/en/join-the-team'
      fullPath: '/en/join-the-team'
      preLoaderRoute: typeof EnJoinTheTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/investors': {
      id: '/en/investors'
      path: '/en/investors'
      fullPath: '/en/investors'
      preLoaderRoute: typeof EnInvestorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/g-struct': {
      id: '/en/g-struct'
      path: '/en/g-struct'
      fullPath: '/en/g-struct'
      preLoaderRoute: typeof EnGStructRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/etw-2026-partners': {
      id: '/en/etw-2026-partners'
      path: '/en/etw-2026-partners'
      fullPath: '/en/etw-2026-partners'
      preLoaderRoute: typeof EnEtw2026PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/enterprise': {
      id: '/en/enterprise'
      path: '/en/enterprise'
      fullPath: '/en/enterprise'
      preLoaderRoute: typeof EnEnterpriseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/contact': {
      id: '/en/contact'
      path: '/en/contact'
      fullPath: '/en/contact'
      preLoaderRoute: typeof EnContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/about-guillermo': {
      id: '/en/about-guillermo'
      path: '/en/about-guillermo'
      fullPath: '/en/about-guillermo'
      preLoaderRoute: typeof EnAboutGuillermoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/articulos/$slug': {
      id: '/articulos/$slug'
      path: '/$slug'
      fullPath: '/articulos/$slug'
      preLoaderRoute: typeof ArticulosSlugRouteImport
      parentRoute: typeof ArticulosRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gstruct-waitlist-count': {
      id: '/api/public/gstruct-waitlist-count'
      path: '/api/public/gstruct-waitlist-count'
      fullPath: '/api/public/gstruct-waitlist-count'
      preLoaderRoute: typeof ApiPublicGstructWaitlistCountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gstruct-waitlist': {
      id: '/api/public/gstruct-waitlist'
      path: '/api/public/gstruct-waitlist'
      fullPath: '/api/public/gstruct-waitlist'
      preLoaderRoute: typeof ApiPublicGstructWaitlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/diagnostico-submit': {
      id: '/api/public/diagnostico-submit'
      path: '/api/public/diagnostico-submit'
      fullPath: '/api/public/diagnostico-submit'
      preLoaderRoute: typeof ApiPublicDiagnosticoSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/contact': {
      id: '/api/public/contact'
      path: '/api/public/contact'
      fullPath: '/api/public/contact'
      preLoaderRoute: typeof ApiPublicContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/article-comments': {
      id: '/api/public/article-comments'
      path: '/api/public/article-comments'
      fullPath: '/api/public/article-comments'
      preLoaderRoute: typeof ApiPublicArticleCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/admin/waitlist': {
      id: '/_admin/admin/waitlist'
      path: '/admin/waitlist'
      fullPath: '/admin/waitlist'
      preLoaderRoute: typeof AdminAdminWaitlistRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/reservas': {
      id: '/_admin/admin/reservas'
      path: '/admin/reservas'
      fullPath: '/admin/reservas'
      preLoaderRoute: typeof AdminAdminReservasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/diagnosticos': {
      id: '/_admin/admin/diagnosticos'
      path: '/admin/diagnosticos'
      fullPath: '/admin/diagnosticos'
      preLoaderRoute: typeof AdminAdminDiagnosticosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDiagnosticosRoute: typeof AdminAdminDiagnosticosRoute
  AdminAdminReservasRoute: typeof AdminAdminReservasRoute
  AdminAdminWaitlistRoute: typeof AdminAdminWaitlistRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDiagnosticosRoute: AdminAdminDiagnosticosRoute,
  AdminAdminReservasRoute: AdminAdminReservasRoute,
  AdminAdminWaitlistRoute: AdminAdminWaitlistRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ArticulosRouteChildren {
  ArticulosSlugRoute: typeof ArticulosSlugRoute
  ArticulosIndexRoute: typeof ArticulosIndexRoute
}

const ArticulosRouteChildren: ArticulosRouteChildren = {
  ArticulosSlugRoute: ArticulosSlugRoute,
  ArticulosIndexRoute: ArticulosIndexRoute,
}

const ArticulosRouteWithChildren = ArticulosRoute._addFileChildren(
  ArticulosRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AliadosEtw2026Route: AliadosEtw2026Route,
  ArticulosRoute: ArticulosRouteWithChildren,
  ContactoRoute: ContactoRoute,
  DiagnosticoFriccionEjecutivaRoute: DiagnosticoFriccionEjecutivaRoute,
  EnterpriseRoute: EnterpriseRoute,
  GStructRoute: GStructRoute,
  InversoresRoute: InversoresRoute,
  LoginRoute: LoginRoute,
  PoliticasLegalesRoute: PoliticasLegalesRoute,
  Reestructura11Route: Reestructura11Route,
  SobreGuillermoRoute: SobreGuillermoRoute,
  UneteAlEquipoRoute: UneteAlEquipoRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  EnAboutGuillermoRoute: EnAboutGuillermoRoute,
  EnContactRoute: EnContactRoute,
  EnEnterpriseRoute: EnEnterpriseRoute,
  EnEtw2026PartnersRoute: EnEtw2026PartnersRoute,
  EnGStructRoute: EnGStructRoute,
  EnInvestorsRoute: EnInvestorsRoute,
  EnJoinTheTeamRoute: EnJoinTheTeamRoute,
  EnRestructure11Route: EnRestructure11Route,
  EnIndexRoute: EnIndexRoute,
  ApiPublicArticleCommentsRoute: ApiPublicArticleCommentsRoute,
  ApiPublicContactRoute: ApiPublicContactRoute,
  ApiPublicDiagnosticoSubmitRoute: ApiPublicDiagnosticoSubmitRoute,
  ApiPublicGstructWaitlistRoute: ApiPublicGstructWaitlistRoute,
  ApiPublicGstructWaitlistCountRoute: ApiPublicGstructWaitlistCountRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
